prowjob_namespace: default
pod_namespace: test-pods
plank:
  default_decoration_config:
    utility_images: # using the tag we identified above
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20191219-b8438ff62"
      initupload: "gcr.io/k8s-prow/initupload:v20191219-b8438ff62"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20191219-b8438ff62"
      sidecar: "gcr.io/k8s-prow/sidecar:v20191219-b8438ff62"
    gcs_configuration:
      bucket: prow-test-bucket # the bucket we just made
      path_strategy: explicit
    gcs_credentials_secret: gcs-credentials # the secret we just made
periodics:
- interval: 10m
  name: echo-test
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
postsubmits:
  ahahn15/prow-test:
  - name: test-postsubmit
    decorate: true
    skip-report: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
presubmits:
  ahahn15/prow-test:
  - name: test-presubmit
    decorate: true
    always_run: true
    skip_report: false
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
